# Generated by Django 2.1 on 2021-01-15 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attrition_table',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='No name given', max_length=70)),
                ('phone_number', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,12}$')])),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_group', models.CharField(blank=True, max_length=20, null=True)),
                ('function', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('tenure', models.FloatField(blank=True, default=0.0, null=True)),
                ('tenure_group', models.CharField(blank=True, default='< =1', max_length=10, null=True)),
                ('experience', models.FloatField(blank=True, default=0.0, null=True)),
                ('maritial', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.FloatField(blank=True, default=25.0, null=True)),
                ('hiring_source', models.CharField(max_length=40)),
                ('promoted_before', models.CharField(blank=True, max_length=40, null=True)),
                ('job_role', models.CharField(blank=True, max_length=10, null=True)),
                ('stay_left', models.CharField(max_length=10)),
            ],
        ),
    ]
